# Site settings
title: Daniel Lopez Madrid
description: Self Driving Car Engineer
# baseurl: "/particle" # the subpath of your site, e.g. /blog
url: "https://lopezmadrid.com" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Daniel Lopez
user_description: Autonomous driving is going to completely change the automotive industry and how it works and transform the world as we know it. I am convinced of this and I am making it happen through my role in JLR. It includes the development of new highly automated driving features, support the technical aspects that affect many of the other areas in the vehicle components and design, the development of a consolidated roadmap for the deployment of these technologies into real world products and management and coordination of projects with suppliers and partners.
user_title: Self Driving Car Engineer
email: daniel@lopezmadrid.com
# twitter_username: lorem_ipsum
github_username:  dlopezmadrid

# Google-analytics
google-analytics:
  id: "UA-47969245-5"

exclude: ['package.json', 'src' , 'node_modules']
